import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Culture Gap Visualizer",
  description: "Generated by AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-zinc-950 text-zinc-100">
        {children}
      </body>
    </html>
  );
}
